-- 002_create_core_tables.sql
-- ContractFlow SQL
-- Создание core-таблиц и audit-log


/* =========================
   CORE DICTIONARIES
   ========================= */

CREATE TABLE IF NOT EXISTS core.user_roles (
	role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS core.delivery_channels (
    delivery_channel_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS core.document_statuses (
    document_status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    is_final boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS core.document_types (
    document_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(100) NOT NULL UNIQUE,
    name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS core.generation_statuses (
    generation_status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    name varchar(255) NOT NULL
);


/* =========================
   CORE USERS
   ========================= */

CREATE TABLE IF NOT EXISTS core.users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    full_name varchar(255) NOT NULL,
    role_id integer NOT NULL REFERENCES core.user_roles(role_id),
    email varchar(255),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT now()
);


/* =========================
   LEGAL ENTITIES
   ========================= */

CREATE TABLE IF NOT EXISTS core.legal_entities (
    legal_entity_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(500) NOT NULL,
    short_name varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS core.legal_entity_signatories (
    signatory_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_entity_id integer NOT NULL REFERENCES core.legal_entities(legal_entity_id),
    position_nom varchar(255) NOT NULL, -- должность в именительном падеже
    position_gen varchar(255),			-- должность в родительном падеже
    full_name_nom varchar(255) NOT NULL,-- ФИО в именительном падеже
    full_name_gen varchar(255),			-- ФИО в родительном падеже
    initials_lastname varchar(100),		-- И.О. Фамилия
    legal_basis_gen varchar(255),		-- основание полномочий в родительном падеже
    is_active boolean NOT NULL DEFAULT true
);


/* =========================
   COUNTERPARTIES
   ========================= */

CREATE TABLE IF NOT EXISTS core.counterparties (
    counterparty_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(500) NOT NULL,
    short_name varchar(255),
    legal_form varchar(50) NOT NULL,
    counterparty_type varchar(50) NOT NULL,
    inn varchar(12) NOT NULL UNIQUE,
    kpp varchar(9),
    ogrn varchar(15),
    legal_address text,
    mailing_address text,
    phone_number varchar(100),
    email_address varchar(255),

    CONSTRAINT chk_counterparty_type
        CHECK (counterparty_type IN ('LEGAL_ENTITY', 'INDIVIDUAL_ENTREPRENEUR')),

    CONSTRAINT chk_inn_format
        CHECK (inn ~ '^[0-9]{10}$|^[0-9]{12}$'),

    CONSTRAINT chk_kpp_format
        CHECK (kpp IS NULL OR kpp ~ '^[0-9]{9}$'),

    CONSTRAINT chk_ogrn_format
        CHECK (ogrn IS NULL OR ogrn ~ '^[0-9]{13}$|^[0-9]{15}$')
);

CREATE TABLE IF NOT EXISTS core.individual_entrepreneur_details (
    counterparty_id integer PRIMARY KEY REFERENCES core.counterparties(counterparty_id),
    passport_data text NOT NULL
);

CREATE TABLE IF NOT EXISTS core.bank_accounts (
    bank_account_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counterparty_id integer NOT NULL REFERENCES core.counterparties(counterparty_id),
    account_number varchar(20) NOT NULL,
    corr_account varchar(20) NOT NULL,
    bik varchar(9) NOT NULL,
    bank_name varchar(255) NOT NULL,
    account_order smallint NOT NULL,

    CONSTRAINT chk_account_number_format
        CHECK (account_number ~ '^[0-9]{20}$'),

    CONSTRAINT chk_corr_account_format
        CHECK (corr_account ~ '^[0-9]{20}$'),

    CONSTRAINT chk_bik_format
        CHECK (bik ~ '^[0-9]{9}$'),

    CONSTRAINT chk_account_order_positive
        CHECK (account_order > 0),

    CONSTRAINT uq_counterparty_account_order
        UNIQUE (counterparty_id, account_order)
);

CREATE TABLE IF NOT EXISTS core.counterparty_signatories (
    signatory_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counterparty_id integer NOT NULL REFERENCES core.counterparties(counterparty_id),
    position_nom varchar(255) NOT NULL,
    position_gen varchar(255),
    full_name_nom varchar(255) NOT NULL,
    full_name_gen varchar(255),
    initials_lastname varchar(100),
    legal_basis_gen varchar(255),
    is_active boolean NOT NULL DEFAULT true
);


/* =========================
   CONTRACTS AND DOCUMENTS
   ========================= */

CREATE TABLE IF NOT EXISTS core.contracts (
    contract_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_entity_id integer NOT NULL REFERENCES core.legal_entities(legal_entity_id),
    counterparty_id integer NOT NULL REFERENCES core.counterparties(counterparty_id),
    created_at timestamp NOT NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,

    CONSTRAINT uq_contract_relation
        UNIQUE (legal_entity_id, counterparty_id)
);

CREATE TABLE IF NOT EXISTS core.document_templates (
    template_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_entity_id integer NOT NULL REFERENCES core.legal_entities(legal_entity_id),
    document_type_id integer NOT NULL REFERENCES core.document_types(document_type_id),
    template_name varchar(255) NOT NULL,
    template_path text NOT NULL,
    template_version varchar(50),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT now(),
    comment text
);

CREATE TABLE IF NOT EXISTS core.contract_documents (
    document_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id integer NOT NULL REFERENCES core.contracts(contract_id),
    document_type_id integer NOT NULL REFERENCES core.document_types(document_type_id),
    document_number varchar(100) NOT NULL UNIQUE,
    document_date date NOT NULL,
    parent_document_id integer REFERENCES core.contract_documents(document_id),
    counterparty_signatory_id integer REFERENCES core.counterparty_signatories(signatory_id),
    legal_entity_signatory_id integer REFERENCES core.legal_entity_signatories(signatory_id),
    is_actual boolean NOT NULL DEFAULT true,
    is_archived boolean NOT NULL DEFAULT false,
    comment text
);


/* =========================
   STATUS HISTORY AND GENERATION LOG
   ========================= */

CREATE TABLE IF NOT EXISTS core.document_status_history (
    status_history_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id integer NOT NULL REFERENCES core.contract_documents(document_id),
    document_status_id integer NOT NULL REFERENCES core.document_statuses(document_status_id),
    delivery_channel_id integer NOT NULL REFERENCES core.delivery_channels(delivery_channel_id),
    status_date timestamp NOT NULL DEFAULT now(),
    changed_by integer REFERENCES core.users(user_id),
    comment text
);

CREATE TABLE IF NOT EXISTS core.document_generation_log (
    generation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id integer NOT NULL REFERENCES core.contract_documents(document_id),
    template_id integer NOT NULL REFERENCES core.document_templates(template_id),
    generated_by integer REFERENCES core.users(user_id),
    generated_at timestamp NOT NULL DEFAULT now(),
    generation_status_id integer NOT NULL REFERENCES core.generation_statuses(generation_status_id),
    generated_file_name varchar(255),
    generated_file_path text,
    error_message text
);


/* =========================
   AUDIT
   ========================= */

CREATE TABLE IF NOT EXISTS audit.audit_log (
    audit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name varchar(255) NOT NULL,
    record_id integer,
    operation varchar(20) NOT NULL,
    old_data jsonb,
    new_data jsonb,
    changed_by integer REFERENCES core.users(user_id),
    changed_at timestamp NOT NULL DEFAULT now(),

    CONSTRAINT chk_audit_operation
        CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'))
);

--ПРОВЕРКА

SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema IN ('core', 'audit')
ORDER BY table_schema, table_name
;