-- 003_create_staging_tables.sql
-- ContractFlow SQL
-- Создание staging-таблиц


/* =========================
   STAGING LOAD BATCHES
   ========================= */

CREATE TABLE IF NOT EXISTS stg.load_batches (
    load_batch_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file_name varchar(255) NOT NULL,
    uploaded_by integer REFERENCES core.users(user_id),
    uploaded_at timestamp NOT NULL DEFAULT now(),

    load_status varchar(50) NOT NULL DEFAULT 'UPLOADED',

    total_rows integer NOT NULL DEFAULT 0,
    valid_rows integer NOT NULL DEFAULT 0,
    warning_rows integer NOT NULL DEFAULT 0,
    invalid_rows integer NOT NULL DEFAULT 0,

    imported_at timestamp,
    comment text,

    CONSTRAINT chk_load_status
        CHECK (load_status IN ('UPLOADED', 'VALIDATED', 'INVALID', 'IMPORTED', 'FAILED')),

    CONSTRAINT chk_load_rows_non_negative
        CHECK (
            total_rows >= 0
            AND valid_rows >= 0
            AND warning_rows >= 0
            AND invalid_rows >= 0
        )
);


/* =========================
   RAW COUNTERPARTY REQUISITES
   ========================= */

CREATE TABLE IF NOT EXISTS stg.counterparty_requisites_raw (
    raw_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_batch_id integer NOT NULL REFERENCES stg.load_batches(load_batch_id),
    row_number integer NOT NULL,

    source_sheet_name varchar(255),
    counterparty_type varchar(50),

    legal_form varchar(50),
    full_name varchar(500),
    short_name varchar(255),

    inn varchar(50),
    kpp varchar(50),
    ogrn varchar(50),
    ogrnip varchar(50),

    position_nom varchar(255),
    position_gen varchar(255),
    full_name_nom varchar(255),
    full_name_gen varchar(255),
    initials_lastname varchar(100),
    legal_basis_gen varchar(255),

    legal_address text,
    mailing_address text,
    phone_number varchar(100),
    email_address varchar(255),
    passport_data text,

    account_number_1 varchar(50),
    corr_account_1 varchar(50),
    bik_1 varchar(50),
    bank_name_1 varchar(255),

    account_number_2 varchar(50),
    corr_account_2 varchar(50),
    bik_2 varchar(50),
    bank_name_2 varchar(255),

    account_number_3 varchar(50),
    corr_account_3 varchar(50),
    bik_3 varchar(50),
    bank_name_3 varchar(255),

    processing_status varchar(50) NOT NULL DEFAULT 'RAW',
    processed_counterparty_id integer REFERENCES core.counterparties(counterparty_id),
    created_at timestamp NOT NULL DEFAULT now(),

    CONSTRAINT chk_stg_counterparty_type
        CHECK (
            counterparty_type IS NULL
            OR counterparty_type IN ('LEGAL_ENTITY', 'INDIVIDUAL_ENTREPRENEUR')
        ),

    CONSTRAINT chk_processing_status
        CHECK (
            processing_status IN (
                'RAW',
                'VALID',
                'VALID_WITH_WARNINGS',
                'INVALID',
                'IMPORTED'
            )
        ),

    CONSTRAINT chk_row_number_positive
        CHECK (row_number > 0)
);


/* =========================
   VALIDATION ERRORS / WARNINGS
   ========================= */

CREATE TABLE IF NOT EXISTS stg.validation_errors (
    validation_error_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_batch_id integer NOT NULL REFERENCES stg.load_batches(load_batch_id),
    raw_id integer NOT NULL REFERENCES stg.counterparty_requisites_raw(raw_id),
    row_number integer NOT NULL,

    field_name varchar(255),
    severity varchar(50) NOT NULL,
    error_code varchar(100) NOT NULL,
    error_message text NOT NULL,

    created_at timestamp NOT NULL DEFAULT now(),

    CONSTRAINT chk_validation_severity
        CHECK (severity IN ('ERROR', 'WARNING')),

    CONSTRAINT chk_validation_row_number_positive
        CHECK (row_number > 0)
);

--ПРОВЕРКА

SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_schema = 'stg'
ORDER BY table_name
;